### PR TITLE
[V2] ipistorm test case fixup for get_family error

### PR DESCRIPTION
**Pull request by sacsant**
ipistorm test case fails to run with following error:
DBLIPIStrom.test: ERROR: 'module' object has no attribute 'get_family'
Use distro.detect().arch statement to check for ppc architecture.
Additionally use online_cpus_count() method instead of online_count().

While at it fix pycodestyle warning against line 91.

Signed-off-by: Sachin Sant sachinp@linux.vnet.ibm.com

### CODE REVIEW

**Comment by sacsant** [comment]
Without the fix:

DBLIPIStrom.test: ERROR: 'module' object has no attribute 'get_family'

With the fix:

# avocado run generic/ipistorm.py
JOB ID     : 21e4636040c4ed4dbd816fcb6615d4dc6059be25
JOB LOG    : /home/upstreamci/avocado-fvt-wrapper/results/job-2021-05-03T04.36-21e4636/job.log
 (1/1) generic/ipistorm.py:DBLIPIStrom.test:  [ 3236.501142] ipistorm: 15 -> 0
[ 3236.501149] ipistorm: 3 -> 4
[ 3236.501153] ipistorm: 14 -> 15
[ 3236.501155] ipistorm: 10 -> 11
[ 3236.501157] ipistorm: 1 -> 2
[ 3236.501159] ipistorm: 5 -> 6
[ 3236.501161] ipistorm: 6 -> 7
....
....

**Review by PraveenPenguin — APPROVED** [review]

**Comment by sacsant** [comment]
Seems like the code in question works with latest level of avocado (83.0) . This issue is seen with older avocado versions.
So question is how do we handle different avocado versions ?

**Comment by harish-24** [comment]
The testcase alone will not be aware of the version of the avocado running. Having said that it is up-to the user to install the necessary avocado version depending on need. Considering that the existing code is on par with the upstream avocado, suggest we close this issue.

**Comment by sacsant** [comment]
Yeah lets close this issue, given that the test case works with latest avocado release.
